<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<RootNamespace>BuildableRover</RootNamespace>
		<AssemblyName>BuildableRover</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<None Update="mod.yaml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="mod_info.yaml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
